name: Release
description: Create a GitHub release and upload the package to PyPI
inputs:
  pypi-api-token:
    description: 'PyPI API token'
    required: true
  tag-name:
    description: 'The name of the tag for the GitHub release'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download packages built by build-and-inspect-python-package
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist

    - name: Download release notes
      uses: actions/download-artifact@v4
      with:
        name: release-notes

    - name: Create a GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: "${{ inputs.tag-name }}"
        body_path: release-notes.md
        token: ${{ inputs.github-token }}

    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-api-token }}
