name: Auto-bump the version
on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:
    inputs:
      dry_run:
        description: Don't actually do the work, just describe it
        default: true
        type: boolean
      new_version:
        description: Set the version to a specific value
        required: false
        type: string
      verbose:
        description: The amount of output detail
        default: 0
        type: choice
        options:
          - "0"
          - "1"
          - "2"

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: |
          python -m pip install generate-changelog bump-my-version build

      - name: Git check
        run: |
          git config --global user.email "bump-my-version@github.actions"
          git config --global user.name "Testing Git"
          git --version
          git config --list

      - name: Generate the changelog and get the release hint
        id: generate-changelog
        run: |
          RELEASE_KIND=$(generate-changelog --output release-hint)
          echo "::notice::Suggested release type is: ${RELEASE_KIND}"
          echo "RELEASE_KIND=$RELEASE_KIND" >> $GITHUB_ENV
          echo "release-kind=$RELEASE_KIND" >> $GITHUB_OUTPUT

      - name: Bump Version auto
        if: ${{ github.event_name != 'workflow_dispatch' }}
        shell: bash
        run: |
          if [[ $RELEASE_KIND != "no-release" ]]; then
            bump-my-version -v "$RELEASE_KIND"
            git push
            git push --tags
          fi

      - name: Bump Version manual
        if: ${{ github.event_name == 'workflow_dispatch' }}
        shell: bash
        env:
          BUMPVERSION_DRY_RUN: ${{ inputs.dry_run }}
          BUMPVERSION_NEW_VERSION: ${{ inputs.tags }}
          BUMPVERSION_VERBOSE: ${{ inputs.verbose }}
        run: |
          case "$RELEASE_KIND" in
            major|minor|patch)
              bump-my-version bump "$RELEASE_KIND"
              if [[ BUMPVERSION_DRY_RUN == "false" ]];  then
                git push
                git push --tags
              fi
              ;;
            release-candidate)
              PR_NUMBER=$(gh pr view --json number -q .number || echo "")
              REVISION=$(git describe --tags --long | awk -F- '{print $2}')
              bump-my-version bump -v --no-tag --no-commit "release_candidate"
              python -m build
              ;;
          esac
      - name: Publish package
        if: ${{ github.event_name == 'workflow_dispatch' && success() }}
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
