name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

defaults:
  run:
    shell: bash

env:
  PYTHONUTF8: "1"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ./.github/actions/setup-python-and-git
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check git is working
        run: |
          git config --global user.email "test-git@github.actions"
          git config --global user.name "Testing Git"
          git --version
          git config --list
      - name: Install test dependencies
        run: pip install '.[test]'
      - name: Test
        run: pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: test-reports/coverage.xml
          flags: python-${{ matrix.python-version }}
          verbose: true # optional (default = false)
          env_vars: OS,PYTHON

  # Upload to Test PyPI.
  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        shell: bash
        run: |
          python -m pip install --disable-pip-version-check --no-python-version-warning build
          python -m pip install --disable-pip-version-check --no-python-version-warning -e .

      - name: Set dev version
        shell: bash
        run: |
          export PR_NUMBER=$(gh pr view --json number -q .number || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "::notice::PR_NUMBER is: ${PR_NUMBER}"
          bump-my-version bump dev bumpversion/__init__.py --no-commit --no-tag --no-configured-files -v
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Package
        shell: bash
        run: |
          python -m build

      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
